### PR TITLE
Update README.md

### LINKED ISSUE #34: Update Readme and Mange the Directories
Anyone who is great at documentation can contribute. 
1. Bring all profile of Contributors to readme
2. Include some animations and Images 
You can display your creativity. Get started now

### PR DESCRIPTION
**Pull request by naikmubashir**
Fixes #34
Added contributors section in Readme.md

### CODE REVIEW

**Comment by naikmubashir** [comment]
You can also add a bot named @add-contributors which automatically adds the names and details of contributors @Ctoic

**Comment by Ctoic** [comment]
Thanks for suggestion @naikmubashir can you add the bot ?

**Comment by naikmubashir** [comment]
I can only if i have access to your repo @Ctoic

**Comment by Ctoic** [comment]
You cannot by forking it ?

**Comment by naikmubashir** [comment]
I'm saying if I add bot to the forked repo it won't add the bot to this repo.

**Comment by Ctoic** [comment]
Okay I will add the bot once I get time , thanks for your suggestion @naikmubashir 👍🏼

**Pull request merged**
