### PR TITLE
added vibrate feature for mobile device for invalid inputs

### PR DESCRIPTION
**Pull request by Temi-Tade**

### CODE REVIEW

**Comment by Ctoic** [comment]
What changes you made ?

**Comment by Temi-Tade** [comment]
I added a vibrate feature for mobile devices when there's is an invalid
input

**Comment by Ctoic** [comment]
Okay great I will merge it now.

**Comment by Temi-Tade** [comment]
Okay thank you so much.

**Comment by Ctoic** [comment]
Thanks for your contribution.

**Pull request merged**
