### PR TITLE
This is the pull request for the design issues which i accidentally pushed into the previous scientific function part

### PR DESCRIPTION
**Pull request by ansh711**

### CODE REVIEW

**Comment by ansh711** [comment]
The additional commits are for the debugging the deepsource: javascript issues ...... Those are present from the start of the code like no brackets in switch case , const reassign , undeclared variable like result application s etc .... I have solved those problems also .....

**Review by Ctoic — APPROVED** [review]

**Comment by ansh711** [comment]
sir can you please check the conflicts and deepsource : javascript check faliure . i am confused what to do

**Comment by ansh711** [comment]
please sir help me

**Comment by Ctoic** [comment]
JavaScript's eval() function is potentially dangerous and is often misused. Using eval() on untrusted code can open a program up to several different injection attacks. The use of eval() in most contexts can be substituted for a better, alternative approach to the problem.
refrence Code 
const obj = { x: "foo" },
    key = "x",
    value = obj[key];

class A {
    foo() {
        // This is a user-defined method.
        this.eval("var a = 0");
    }

    eval() { /* ... * / }
}

**Comment by Ctoic** [comment]
I'm On it

**Comment by ansh711** [comment]
thank you sir

**Comment by Ctoic** [comment]
Again create a pull request now

**Review by Ctoic — APPROVED** [review]
Reviewed Change.

**Comment by ansh711** [comment]
thank you sir

**Comment by ansh711** [comment]
i was just stucked in that step .... really appreciate your help sir . thank you

**Pull request closed without merging**
