### PR TITLE
changes my new pull request

### PR DESCRIPTION
**Pull request by ansh711**

### CODE REVIEW

**Comment by ansh711** [comment]
sir i have started new pull request

**Comment by ansh711** [comment]
some conflicts are there sir ...... but the checks are done good

**Comment by ansh711** [comment]
thank you for merging my two pull requests

**Comment by ansh711** [comment]
it is a pleasure working with you

**Comment by Ctoic** [comment]
Thanks a lot for your contributions.

**Comment by ansh711** [comment]
please let me know if you will start new repo . I would like to work also there

**Comment by ansh711** [comment]
https://www.linkedin.com/in/anshuman-maitra-333198256?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

this is my linkdin account ... can you please follow me to boost my connections .... ? Thank you any way

**Comment by Ctoic** [comment]
Okay great but right now our calculator is not working. I have Ideas to work on we will get in touch

**Comment by ansh711** [comment]
Thank you sir for providing me such a great start in open source contribution..... ❤️

**Comment by Ctoic** [comment]
I wish you best of luck ❤️

**Comment by Ctoic** [comment]
We can Endorse Eachother on linkedin.

**Comment by ansh711** [comment]
Certainly sir

**Comment by Ctoic** [comment]
okay great

**Pull request merged**
