### PR TITLE
Added the hacktoberfest timer

### PR DESCRIPTION
**Pull request by lavish-github**
I have added a hacktoberfest timer to the web page.

image

Kindly review it once and let me know about any kind of changes to be made. Thanks

Refs #69

### CODE REVIEW

**Comment by Ctoic** [comment]
It looks great but if you can adjust the timer at the side of the calculator. it will be better

**Comment by lavish-github** [comment]
Ok. Working on it.

**Comment by Ctoic** [comment]
Go ahead you can do it 👍🏼

**Comment by lavish-github** [comment]
I have tried to implement the requested changes. 

- Moved the HacktoberFest timer to the left side of the calculator

**Before**
image

**After**
image

- Improved some responsiveness

**Before**
image

**After**
image

Any kind of feedback is heartfully welcome. Thanks

**Comment by Ctoic** [comment]
I really appreciate your efforts @lavish-github Thanks for your contributions.

**Review by Ctoic — APPROVED** [review]
Changes Approved!

**Comment by lavish-github** [comment]
No problem. I love to do these kind of problems 🚀

**Pull request merged**
