### PR TITLE
feat: Redesigned buttons of calculator

### LINKED ISSUE #6: feat: Redesigning the tic tac toe game giving a refreshing look.
As the title suggests, this issue is regarding the styling. So get your CSS skills to work by improving the design of the overall application (or maybe a part of it)

### PR DESCRIPTION
**Pull request by shivam-sharma-03**
Description
This Pull Request addresses issue #6 , which focused on enhancing the styling of the calculator component in our project. Redesigned the calculator interface using my CSS skills by improving the design of the overall application, also improved some parts of Html to improve calculators functioning.

Changes Made
In this PR, the following changes have been made to improve the calculator's styling:

Calculator buttons UI Redesign: The calculator's layout has been redesigned with a cleaner and more modern look. This includes improved button styling, color schemes, and font choices.

Consistent Styling: All elements of the calculator, including buttons, display, and input fields, now follow a consistent styling theme throughout the application.

Related Issue
Fixes #6

Screenshots:

After:-
Calculator After (2)

### CODE REVIEW

**Comment by shivam-sharma-03** [comment]
hey @Ctoic i have made a PR for the issue #6 please review and also please add Hactoberfest and Hactoberfest-Accepted label o this PR.

**Comment by Ctoic** [comment]
Thanks @shivam-sharma-03  for making things clear. Now I have merged your pull request with both hactoberfest-accepted and hactoberfest labels.

**Comment by Ctoic** [comment]
And here is the Flask Repo which is a basic CRUD Application but it will be great if we can make it more attractive by adding CSS and Javascript. Try to add search functionality for the tasks if possible.

**Comment by Ctoic** [comment]
https://github.com/Ctoic/Flask-Harry

**Comment by shivam-sharma-03** [comment]
Thank you @Ctoic for your, reviews about my Css skills and i will surly try to contribute in the flask repo that you shared with me.
Thank you once again.

**Comment by Ctoic** [comment]
No Problem @shivam-sharma-03 you are doing great. Let's learn together

**Comment by shivam-sharma-03** [comment]
@Ctoic i am unable to see the label on either PRs

Screenshot:-
no label

**Comment by Ctoic** [comment]
I have added both on the latest pull request. I can see them but I don't know why they are not visible to you.

**Pull request merged**
