### PR TITLE
corrected the square root bug

### LINKED ISSUE #67: Square root button not working
I am not able to use square root button

image

Neither it is working in any mathematical expression

### PR DESCRIPTION
**Pull request by lavish-github**
I have tried to fix the issue. It is working in the mathematical expression also.

Fixes #67 

image

Moreover, it is accepting expression in the format of √+9 and √-9 also.

### CODE REVIEW

**Comment by lavish-github** [comment]
Is there any problem with this PR?

**Review by Ctoic — APPROVED** [review]
Accepted !

**Comment by Ctoic** [comment]
You have done some unnecessary changes like deleting a tag and again adding it @lavish-github

**Comment by lavish-github** [comment]
I am extremely for my mistake, but I am not able to understand where I have made those changes😅. Regarding `index.html`, some of the changes have been made automatically by the linter extension. If something else is there, then I request you to kindly let me know, so that I can prevent such mistakes in future. Thanks

**Comment by Ctoic** [comment]
No worries, but please keep in mind that making changes without a specific purpose can create a negative impression. Overall, it's fine, but next time, change something only if it has a meaningful purpose; otherwise, leave it as it was before. 😄

**Comment by lavish-github** [comment]
Sure

**Pull request merged**
